apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:latest
        imagePullPolicy: Always
        name: mongo
        command: ["mongod", "--bind_ip_all", "--smallfiles"]
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: "mongo-volume"
